### ISSUE TITLE
Error with Extended User

### ISSUE THREAD

**Issue by joseamaya** [wachjose88/django-lti-provider-auth#1]
Hello, we are using django-lti-provider-auth but we are getting the following error:
ERRORS:
lti_provider.Consumer.user: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
We are using an extended user model.

Greetings.

**Comment by wachjose88** [comment]
Thanks. I can confirm the problem with extended user models. I will release a fix soon.

**Comment by wachjose88** [comment]
I released a fix. Please test version 0.0.8
https://pypi.org/project/django-lti-provider-auth/0.0.8/
