### ISSUE TITLE
Django > 4

### ISSUE THREAD

**Issue by joao-n-silva** [wachjose88/django-lti-provider-auth#2]
I'm running you application in django 4.0.3 and some of the functions you use are incompatible with this new version:
-     ugettext_lazy 
-     url

You only have to change the following files:

apps.py, models.py and field_validator.py

-     from django.utils.translation import ugettext_lazy as _
    to
-     jango.utils.translation import gettext_lazy as _

urls.py

-     from django.conf.urls import url
    to
-     from django.urls import re_path
and
-     replace url to re_path 

After these changes all the remaining code is running and allows the creation of a simple provider that already interacts with moodle

I don't know if this changes work with django 3

best regards

**Comment by wachjose88** [comment]
Thanks for pointing this out. I will only support the current LTS version of Django. This means that the adaptions you mentioned will be available for Django 4.2 in April 2023.
